url: "http://women-at-kaust.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Women at KAUST" # the name of your site, e.g. ACME Corp.
description: ""


theme: academic